import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#1b1b1b",
        "on-primary-fixed": "#001c3a",
        "error": "#ba1a1a",
        "surface-variant": "#e2e2e2",
        "on-tertiary-fixed-variant": "#454747",
        "on-error": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "outline": "#74777f",
        "surface-tint": "#476083",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#43474e",
        "surface": "#f9f9f9",
        "outline-variant": "#c4c6cf",
        "tertiary-fixed": "#e2e2e2",
        "inverse-on-surface": "#f1f1f1",
        "inverse-primary": "#afc8f0",
        "on-secondary": "#ffffff",
        "surface-bright": "#f9f9f9",
        "surface-container": "#eeeeee",
        "secondary": "#006d31",
        "primary": "#000613",
        "primary-container": "#001f3f",
        "on-primary-fixed-variant": "#2f486a",
        "surface-dim": "#dadada",
        "tertiary-container": "#1d1f1f",
        "error-container": "#ffdad6",
        "on-background": "#1b1b1b",
        "on-tertiary-fixed": "#1a1c1c",
        "on-secondary-fixed": "#00210a",
        "inverse-surface": "#303030",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d4e3ff",
        "on-primary-container": "#6f88ad",
        "primary-fixed-dim": "#afc8f0",
        "on-secondary-fixed-variant": "#005324",
        "surface-container-high": "#e8e8e8",
        "on-secondary-container": "#007234",
        "secondary-fixed-dim": "#71dc8a",
        "secondary-fixed": "#8ef9a4",
        "tertiary": "#040606",
        "surface-container-highest": "#e2e2e2",
        "secondary-container": "#8bf6a1",
        "background": "#f9f9f9",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary-container": "#858687",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-gap": "160px",
        "component-gap": "24px",
        "margin-mobile": "24px",
        "gutter": "32px",
        "margin-desktop": "80px",
      },
      fontFamily: {
        montserrat: ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["64px", { lineHeight: "1.0", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["40px", { lineHeight: "1.1", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.5", letterSpacing: "0.02em", fontWeight: "300" }],
        "label-sm": ["12px", { lineHeight: "1.4", fontWeight: "300" }],
      },
    },
  },
  plugins: [],
};

export default config;
